linters:
  enable:
   - asasalint
   - asciicheck
   - bidichk
   - bodyclose
   - containedctx
   - contextcheck
   - copyloopvar
   - decorder
   - dogsled
   - dupl
   - dupword
   - durationcheck
   - errcheck
   - errname
   - errorlint
   - exhaustive
   - exportloopref
   - fatcontext
   - ginkgolinter
   - gocheckcompilerdirectives
   - gochecksumtype
   - goconst
   - gocyclo
   - godox
   - gofmt
   - goheader
   - goimports
   - gomoddirectives
   - gomodguard
   - goprintffuncname
   - gosimple
   - gosmopolitan
   - govet
   - grouper
   - importas
   - inamedparam
   - ineffassign
   - interfacebloat
   - intrange
   - loggercheck
   - maintidx
   - makezero
   - mirror
   - misspell
   - nakedret
   - nilerr
   - nilnil
   - nolintlint
   - nosprintfhostport
   - predeclared
   - promlinter
   - reassign
   - rowserrcheck
   - sloglint
   - spancheck
   - sqlclosecheck
   - staticcheck
   - testableexamples
   - testifylint
   - thelper
   - tparallel
   - unconvert
   - unparam
   - unused
   - wrapcheck
   - zerologlint

  disable:
   - canonicalheader
   - cyclop
   - depguard
   - err113
   - errchkjson
   - exhaustruct
   - forbidigo
   - forcetypeassert
   - funlen
   - gci
   - gochecknoglobals
   - gochecknoinits
   - gocognit
   - gocritic
   - godot
   - gofumpt
   - gomnd
   - gosec
   - ireturn
   - lll
   - mnd
   - musttag
   - nestif
   - nlreturn
   - noctx
   - nonamedreturns
   - paralleltest
   - perfsprint
   - prealloc
   - protogetter
   - revive
   - stylecheck
   - tagalign
   - tagliatelle
   - tenv
   - testpackage
   - usestdlibvars
   - varnamelen
   - wastedassign
   - whitespace
   - wsl
